#!/usr/bin/tcsh
if ($1 == all) then
    if ( -e towel ) set T
    mv ??[^midxburn]* ~/pa3/items >& ~/X && echo "You pick things up." ||\
    ( ls ??[xumbird]* >& ~/X && echo "You cannot pick that up." ) || \
    echo "There is nothing here to get."
else if ( ! -e $1 ) then
    echo "You cannot see that here."
else if ( $1 =~ ??[xumbird]* ) then
    echo "You cannot pick that up."
else
    if ( $1 == "disk" || $1 == "floppy" ) then
        mv disk floppy ~/pa3/items/ >& ~/X
    else if ( $1 == "life" || $1 == "preserver" ) then
        mv life preserver ~/pa3/items/ >& ~/X
    else if ( $1 == "towel" ) then
        mv towel ~/pa3/items/ >& ~/X
        set T
    else
        mv $1 ~/pa3/items/ >& ~/X
    endif
    echo "You pick up the $1"
endif

if ( $?T ) then
    if ( ! -e Tex ) then
        mv .d d >& ~/X
        echo "Taking the towel reveals a hole in the floor."
        mv .hiddenhole _hiddenhole >& ~/X
        cat _hiddenhole > Tex
    endif
endif
