#!/bin/tcsh
if ($1 == all) then
    if ( -e towel ) set T = 1
    mv ??[^midxburn]* ~/pa3/items >& ~/X && echo "You pick things up." ||\
    ( ls ??[xumbird]* >& ~/X && echo "You cannot pick that up." ) || \
    echo "There is nothing here to get."
else if ( ! -e $1 ) then
    echo "You cannot see that here."
else if ( $1 =~ ??[xumbird]* ) then
    echo "You cannot pick that up."
else
    if ( $1 == "disk" || $1 == "floppy" ) then
        if ( -e ~/items/$1 ) then
            mv disk floppy ~/items/ >& ~/X
            echo "You pick up the disk and the floppy"
        endif
    else if ( $1 == "life" || $1 == "preserver" ) then
        if ( -e ~/items/$1 ) then
            mv life preserver ~/items/ >& ~/X
            echo "You pick up the preserver and the life"
        endif
    else if ( $1 == "towel" ) then
        mv towel ~/items/ >& ~/X
        echo "You pick up the $1"
        set T = 1
    else
        mv $1 ~/items/ >& ~/X
        echo "You pick up the $1"
    endif
endif

if ( $T ) then
    mv .d d 2> ~/X
    echo "Taking the towel reveals a hole in the floor."
    mv .hiddenhole _hiddenhole 2> ~/X