#!/usr/bin/tcsh
if ( ! -e ~/pa3/items/$1 ) then
    echo You don\'t have that.
    exit
else if ( $3 == "" ) then
    echo You must supply an indirect object.
    exit
endif

if ( $1 == disk ) set argv[1] = floppy
if ( $1 == life ) set argv[1] = preserver

switch ( $argv[3] )
    case pc: 
    case IBM:
    case ibm:
    case drive:
    case computer:
        set argv[3] = PC
endsw

if ( ! -e ~/pa3/items/$3 && ! -e $3 ) then
    echo that indirect object is not here.
else if ( $3 == urinal ) then
    echo You hear it plop down in some water below.
    mv ~/pa3/items/$1 ~/pa3/holdtreasure >& ~/X
    if ( $1 == disk ) rm ~/items/floppy >& ~/X
    if ( $1 == life ) rm ~/items/preserver >& ~/X
else if ( $3 == box ) then
    if ( $1 == key ) then
        mv ~/pa3/items/$1 ~/pa3/holdkey >& ~/X
        rm box >& ~/X
        echo As you drop the key, the box begins to shake.  Finally it explodes\
        \\nwith a bang.  The key seems to have vanished\!
    else
        echo You can\'t put that in the key box\!
    endif
else if ( $3 == PC ) then
    if ( $1 == floppy ) then
        mv ~/pa3/items/$1 ./.$1 >& ~/X
        rm ~/pa3/items/disk >& ~/X
    else
        echo You can\'t put that in the PC\!
    endif
else
    echo I don\'t know how to combine those objects.  Perhaps you should\
        \\njust try dropping it.
endif
